### ISSUE TITLE
Status code 500 on private profiles

### ISSUE THREAD

**Issue by JoshCode** [Fuyukai/OWAPI#229]
## Issue

New Overwatch patch introduced private profiles. API calls on private profile results in 500 error.

Output:
```
{
    "msg": "please report this!",
    "exc": "IndexError('list index out of range',)",
    "error": 500
}
```

## Links that cause the issue

`https://owapi.net/api/v3/u/Dexcuracy-2811/stats`

**Comment by Fuyukai** [comment]
When I go on summer holiday I will fix this

**Comment by Doezer** [comment]
Please note that the comp rank is still available even for private profiles.
Issue is that Blizzard has made all profiles private by default.

**Comment by Fuyukai** [comment]
"Fixed" by 5be1032bcc2e245e59fbe87eb7f82734d6785439.

**Comment by Doezer** [comment]
@Fuyukai Would it be possible to still get the available information from the private profile? (as precised above)

Since Blizzard switched every account to private by default, that means all applications relying on OWAPI cannot work anymore.

**Comment by Fuyukai** [comment]
Yes, I do plan on adding that info back at some point, but I don't have the time (nor will) to re-work the parsing spaghetti to get the values.
